# Generated by Django 3.1.3 on 2020-11-09 20:35

from django.db import migrations, models
import django.utils.timezone


class RequestToHIS(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RequestToHIS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=50)),
                ('method', models.CharField(max_length=10)),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
